// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PointDatabase;

#nullable disable

namespace PointDatabase.Migrations
{
    [DbContext(typeof(Entities))]
    [Migration("20220808111143_Renamed")]
    partial class Renamed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PointDatabase.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Adressenavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adressetilleggsnavn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BNR")
                        .HasColumnType("int");

                    b.Property<int?>("Bruksenhetsnummer")
                        .HasColumnType("int");

                    b.Property<int>("GNR")
                        .HasColumnType("int");

                    b.Property<int>("Nummer")
                        .HasColumnType("int");

                    b.Property<int>("PoststedId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TS")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Undernummer")
                        .HasColumnType("int");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PoststedId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("PointDatabase.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AdressId")
                        .HasColumnType("int");

                    b.Property<string>("EPSG")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<double>("Longtitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("TS")
                        .HasColumnType("datetime2");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdressId");

                    b.HasIndex("LocationId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("PointDatabase.Fylke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Fylkesnavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fylkesnummer")
                        .HasColumnType("int");

                    b.Property<int>("HelseRegionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TS")
                        .HasColumnType("datetime2");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HelseRegionId");

                    b.ToTable("Fylke");
                });

            modelBuilder.Entity("PointDatabase.HealthRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Bruker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TS")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HealthRegions");
                });

            modelBuilder.Entity("PointDatabase.Kommune", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Bruker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FylkeId")
                        .HasColumnType("int");

                    b.Property<string>("Kommunenavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kommunenummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TS")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FylkeId");

                    b.ToTable("Kommune");
                });

            modelBuilder.Entity("PointDatabase.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Bruker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Orgnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TS")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Orgnummer")
                        .IsUnique();

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("PointDatabase.Point", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Bruker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BygningId")
                        .HasColumnType("int");

                    b.Property<int?>("FartøyId")
                        .HasColumnType("int");

                    b.Property<int?>("RomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TS")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BygningId");

                    b.HasIndex("FartøyId");

                    b.HasIndex("RomId");

                    b.ToTable("Points");
                });

            modelBuilder.Entity("PointDatabase.Poststed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Bruker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KommuneId")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TS")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KommuneId");

                    b.ToTable("Poststed");
                });

            modelBuilder.Entity("PointDatabase.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Bruker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BygningId")
                        .HasColumnType("int");

                    b.Property<int>("Etasje")
                        .HasColumnType("int");

                    b.Property<int>("KontaktPersonID")
                        .HasColumnType("int");

                    b.Property<string>("Romnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TS")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BygningId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("PointDatabase.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Bruker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FartøyTypeId")
                        .HasColumnType("int");

                    b.Property<int>("LokasjonId")
                        .HasColumnType("int");

                    b.Property<string>("Navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Registreringsnummer")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("TS")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FartøyTypeId");

                    b.HasIndex("LokasjonId");

                    b.HasIndex("Registreringsnummer")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("PointDatabase.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Bruker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Navn")
                        .HasColumnType("int");

                    b.Property<DateTime>("TS")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes");
                });

            modelBuilder.Entity("PointDatabase.Address", b =>
                {
                    b.HasOne("PointDatabase.Poststed", "Poststed")
                        .WithMany()
                        .HasForeignKey("PoststedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poststed");
                });

            modelBuilder.Entity("PointDatabase.Building", b =>
                {
                    b.HasOne("PointDatabase.Address", "Adress")
                        .WithMany()
                        .HasForeignKey("AdressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PointDatabase.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adress");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("PointDatabase.Fylke", b =>
                {
                    b.HasOne("PointDatabase.HealthRegion", "HelseRegion")
                        .WithMany()
                        .HasForeignKey("HelseRegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HelseRegion");
                });

            modelBuilder.Entity("PointDatabase.Kommune", b =>
                {
                    b.HasOne("PointDatabase.Fylke", "Fylke")
                        .WithMany()
                        .HasForeignKey("FylkeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fylke");
                });

            modelBuilder.Entity("PointDatabase.Point", b =>
                {
                    b.HasOne("PointDatabase.Building", "Bygning")
                        .WithMany()
                        .HasForeignKey("BygningId");

                    b.HasOne("PointDatabase.Vehicle", "Fartøy")
                        .WithMany()
                        .HasForeignKey("FartøyId");

                    b.HasOne("PointDatabase.Room", "Rom")
                        .WithMany()
                        .HasForeignKey("RomId");

                    b.Navigation("Bygning");

                    b.Navigation("Fartøy");

                    b.Navigation("Rom");
                });

            modelBuilder.Entity("PointDatabase.Poststed", b =>
                {
                    b.HasOne("PointDatabase.Kommune", "Kommune")
                        .WithMany()
                        .HasForeignKey("KommuneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kommune");
                });

            modelBuilder.Entity("PointDatabase.Room", b =>
                {
                    b.HasOne("PointDatabase.Building", "Bygning")
                        .WithMany()
                        .HasForeignKey("BygningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bygning");
                });

            modelBuilder.Entity("PointDatabase.Vehicle", b =>
                {
                    b.HasOne("PointDatabase.VehicleType", "FartøyType")
                        .WithMany()
                        .HasForeignKey("FartøyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PointDatabase.Location", "Lokasjon")
                        .WithMany()
                        .HasForeignKey("LokasjonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FartøyType");

                    b.Navigation("Lokasjon");
                });
#pragma warning restore 612, 618
        }
    }
}
